### ISSUE TITLE
1.1.0 doesn't accept -u option

### ISSUE THREAD

**Issue by drewhamilton** [saket/startship#11]
After updating to 1.1.0 and trying to use the new `-u` option, I get an error:
> Error: no such option: "-u".

To check why that could be, I downloaded [startship.zip](https://github.com/saket/startship/releases/tag/1.1.0) and started looking around. The lib/ directory includes Picnic's jar, so it's not just a copy of 1.0.0. But digging into the included startship.jar, I find that `ReleaseCommand.class` does not appear to include the new private `username` or `password` properties. A clean distZip doesn't have this problem, so I think somehow an old commit got built for this release.

Looking at the release steps it seems like I can probably release a fix? Just opening this in case I forget or run into problems.

**Comment by saket** [comment]
Whoops I'm not sure how that happened. Yeah wanna try building a release zip?

**Comment by drewhamilton** [comment]
Fixed in 1.1.1
