### ISSUE TITLE
Support configurable ossrh urls

### ISSUE THREAD

**Issue by brianf** [saket/startship#12]
Just stumbled on this and it looks great. As part of the short term scaling I mentioned on Twitter, we have created multiple servers and thus people will need to tell your tool which one they are on. If you make the oss.Sonatype.org part of the url configurable, then this should be good. Many people will be switching over to some of the new hosts en mass today and next week.

**Comment by brianf** [comment]
Here's an example of the new shard url:  https://s01.oss.sonatype.org

**Comment by drewhamilton** [comment]
Is each user and/or project assigned one of these automatically? How do they know which one they're on?

Will `oss.sonatype.org` still be a sensible default or will eventually everyone have one of many different shards?

Would it make sense to accept just `s01` as the parameter value or should it be the whole base URI?

**Comment by drewhamilton** [comment]
[This blog post](https://central.sonatype.org/articles/2021/Feb/23/new-users-on-s01osssonatypeorg/) answers my questions:
* Users from before 25 Feb 2021 will stay on `oss.sonatype.org`, so it probably makes sense to leave this the default.
* Newer users are on `s01.oss.sonatype.org`. I think it makes sense to accept either `s01` or the full `s01.oss.sonatype.org` as the parameter value, and append `oss.sonatype.org` if it's not part of the argument.

**Comment by saket** [comment]
Accepting `s01` sounds good. Accepting the full URL would have probably made sense if `startship` wasn't tied to Sonatype Nexus.
