### ISSUE TITLE
Document required Gradle properties

### ISSUE THREAD

**Issue by drewhamilton** [saket/startship#4]
I'm starting to use this on a personal project and it took some digging to figure out the names of the properties that Startship expects in gradle.properties. The error message also mentions the option of using `-c` but doesn't say the format of the arguments.

I'd be happy add either or both of these to the readme if you're open to it.

**Comment by saket** [comment]
Yeah that'd be very helpful. Do you think mentioning the required properties in the README as well as including the expected format in the error message be sufficient? 

A PR will be very appreciated!

**Comment by drewhamilton** [comment]
Yep exactly. I assume `-c` takes a single argument "group:artifact:version"?

I expect I'll be able to open the PR within a few days.
