### ISSUE TITLE
Clarify ambiguity around use of artifact name

### ISSUE THREAD

**Issue by drewhamilton** [saket/startship#5]
As input, `startship release` requires the group name, artifact name, and version.

Many projects, including mine, publish multiple artifacts, so the requirement for an artifact name was initially concerning. As it turns out, it's not a problem: the entire multi-artifact repository is closed and then released as expected. But the requirement of an artifact name as input and the messages shown in the terminal along the way give the false impression that only one of the artifacts is being released.

So I'd like to:
1. Rephrase the command-line messages to avoid suggesting that only one artifact is released.
2. Document what exactly the artifact name is used for.
3. If possible, make the artifact name optional: Identify the staging repository only by group and version, failing only if there is more than one match. (If this is possible, maybe the version can also be optional.)

**Comment by saket** [comment]
TIL. I have zero experience releasing multi-artifact projects so I did not account for it. I agree with all your suggestions. Matching only group and version sounds good enough to me!

**Comment by drewhamilton** [comment]
For example, OkHttp has the main OkHttp artifact plus Logging Interceptor, MockWebServer, and a [bunch of others](https://mvnrepository.com/artifact/com.squareup.okhttp3).

OK I will dive into the source code and see if I can do a PR for this one too!

**Comment by drewhamilton** [comment]
So part 3 is difficult because you use the artifact ID to check the maven-metadata for the updated version. Will have to think about it a bit more.

**Comment by saket** [comment]
Riiight. I wanted to look if Sonatype has an API for inspecting artifacts inside staged repositories but I couldn't get there. Maybe startship can show a warning message and ask for user's input if the maven coordinates don't match instead of throwing an error? The user can choose to continue anyway. Wdyt?

**Comment by drewhamilton** [comment]
> I wanted to look if Sonatype has an API for inspecting artifacts inside staged repositories

Exactly, this would be ideal. "couldn't get there" meaning you didn't have time to dig through the APIs, or you determined no such API exists?

>  Maybe startship can show a warning message and ask for user's input if the maven coordinates don't match instead of throwing an error?

Which error is this?

**Comment by saket** [comment]
> "couldn't get there" meaning you didn't have time to dig through the APIs, or you determined no such API exists?

Didn't have enough time 😄 

> Which error is this?

Here you go: https://github.com/saket/startship/blob/1874f6437ca54fd5bb7a981efe4d6bb11244899b/src/main/kotlin/nevam/ReleaseCommand.kt#L118

**Comment by drewhamilton** [comment]
OK I think I figured out how to do this. As far as I can tell it's not documented as part of the API, but your current validation via `NexusApi.stagingMavenMetadata` was my clue to figure it out.

`/repositories/{repositoryIdKey}/content/` is the content directory for the (staging) repository, and from there it's effectively a file system. The response looks like this:
```xml
<content>
  <data>
    <content-item>
      <resourceURI>https://oss.sonatype.org/service/local/repositories/{repositoryIdKey}/content/{directoryName}/</resourceURI>
      <relativePath>/{directoryName}/</relativePath>
      <text>{directoryName}</text>
      <leaf>false</leaf>
      <lastModified>2020-11-21 10:27:47.0 UTC</lastModified>
      <sizeOnDisk>-1</sizeOnDisk>
    </content-item>
  </data>
</content>
```
Where `directoryName` is the first part of the group being published. `directoryName` can be appended to the path to read that directory, and so on through each directory. The `<data>` element will have multiple `<content-item>` children if it has multiple child directories.

From here it depends on where you want to draw the line between strict validation and too many network calls. If the user of the command provides a group, multiple artifact names, and a version; the tool can either (1) validate that those artifacts exist in the repository, or (2) validate that **only** _those artifacts_ at _that group_ with _that version_ exist in the repository. The latter option would require making the above API call a bunch of times to validate no extra directories exist that don't match each subgroup/artifact/version path.

Even with the extra API calls I think (2) is the better option, to ensure you don't accidentally publish something that can never be unpublished.

Finally, there is a question of API design. I envision 3 new command line options: `-g` for the group, `-a` for a list of artifacts, and `-v` for the version. I guess a user would have to either (a) pass all 3 of those, (b) pass the existing `-c`, or (c) pass none of these to rely on the Gradle properties. I'm not sure if there are any command line conventions around mutually-required and/or mutually-exclusive options, or if Clikt has any conveniences to make this easy. Also not sure what the delimiting character should be for the `-a` list.

So I guess let me know if you have any opinions or knowledge on anything I summarized in this comment, otherwise I'll work my way through implementing it!

**Edit:** Implementing option (2) from above requires a tree of directories to check for, which is complicated enough that I don't want to dive into it for now. So instead I'll just do option (1) using the existing metadata check and allowing multiple artifacts.

**Comment by saket** [comment]
I just got a chance to see this. I love this idea.

I agree that validating all groups (option 2) would be great but may not be worth doing it for the complexity. Option 1 is still useful nonetheless. 

> I guess a user would have to either (a) pass all 3 of those, (b) pass the existing -c, or (c) pass none of these to rely on the Gradle properties. I'm not sure if there are any command line conventions around mutually-required and/or mutually-exclusive options, or if Clikt has any conveniences to make this easy. Also not sure what the delimiting character should be for the -a list.

Is this still a challenge? I saw your proposed syntax in #9 (`$ startship release -c com.example:nicolascage,dianekruger:4.2.0`) and that looks like a solved problem now?

**Comment by drewhamilton** [comment]
Yep, if you like the `-c` with commas then I'd say it's solved. I like that it doesn't require new options or complex rules about which options take precedence over others.

**Comment by saket** [comment]
Yeah sounds good then. Let's go with this!
