### ISSUE TITLE
Add command line options for custom Gradle property names

### ISSUE THREAD

**Issue by drewhamilton** [saket/startship#6]
Use case: I publish some personal open source libraries as well as an open source library under my company's name. My company's Sonatype login is different than my personal one. I'd like to use Startship for both.

This is currently impossible because `startship release` implicitly looks for `SONATYPE_NEXUS_USERNAME` and `SONATYPE_NEXUS_PASSWORD` Gradle properties. If the names of these properties were configurable via command line option, then I could set different values when I publish each of my/my company's libraries.

Alternatively, the username and password themselves could be the command line options. But then I can't put a copy/paste-able command in my release instructions.

**Comment by saket** [comment]
Being able to pass options sounds great to me. Something along the lines of `startship release -u USERNAME -p PASSWORD`?

**Comment by drewhamilton** [comment]
Is it a security concern that this would put the password in plain text in the command history? Is there a standard way to avoid this in command line tools?

**Comment by saket** [comment]
Hmmm I actually don't know if that's an issue. Should `startship` look for nexus credentials in the project's `gradle.properties` then?

**Comment by drewhamilton** [comment]
No, they wouldn't be there either because you wouldn't check the password into the project repo. So the machine's gradle.properties is the right place to look.

I just want a way to change which property name it looks for so I can use one password from gradle.properties for one project, and another password from the same gradle.properties for a different project.

**Comment by saket** [comment]
> I just want a way to change which property name it looks for so I can use one password from gradle.properties for one project, and another password from the same gradle.properties for a different project.

Sure let's go with that!
